/**
 * Converter library public surface.
 *
 * Preferred entry points:
 * - `convertSource` — end-to-end single React/TSX source → Elementor JSON + report
 * - `convertSectionInput` / `resolveSectionInput` — virtual section folder map → same pipeline
 * - `convert` — styled IR → Elementor JSON + report
 * - `analyzeReactSource` / `resolveStyles` — lower pipeline stages
 *
 * Phase 10: `compat/` static Elementor Free 4.2.4 checks (runtime import BLOCKED here).
 *
 * Lower-level APIs (`convertToNativeElementor`, `convertToElementor`, …)
 * remain available and backward-compatible.
 */

export {
  CONVERSION_DECISION_ORDER,
  ConversionDecisionSchema,
  ConversionOutcomeSchema,
  DiagnosticSeveritySchema,
  UnsupportedReasonCodeSchema,
  type ConversionDecision,
  type ConversionOutcome,
  type DiagnosticSeverity,
  type UnsupportedReasonCode,
} from "./types/decisions";

export {
  IR_SCHEMA_VERSION,
  IR_RECOMMENDED_BREAKPOINTS,
  IrDocumentSchema,
  IrNodeKindSchema,
  IrNodeSchema,
  IrNodeStatusSchema,
  IrStyleSchema,
  IrProvenanceSchema,
  IrDiagnosticSchema,
  IrUncertaintySchema,
  parseIrDocument,
  safeParseIrDocument,
  normalizeIrDocument,
  canonicalizeIrJson,
  type IrDocument,
  type IrNode,
  type IrNodeKind,
  type IrNodeStatus,
  type IrStyle,
  type IrProvenance,
  type IrDiagnostic,
  type IrUncertainty,
  type IrRecommendedBreakpoint,
} from "./ir";

export {
  CATALOG_SCHEMA_VERSION,
  ELEMENTOR_DOCUMENT_VERSION,
  EMPTY_ELEMENTOR_FREE_CATALOG_STUB,
  ElementorFreeCatalogSchema,
  DEFAULT_ELEMENTOR_FREE_TARGET,
  SUPPORTED_ELEMENTOR_FREE_TARGETS,
  loadElementorFreeCatalog,
  listAvailableElementorFreeCatalogTargets,
  canUseControl,
  canUseWidget,
  checkFreeCompliance,
  getCatalogWidget,
  isProDenylisted,
  type ElementorFreeCatalog,
  type FreeComplianceResult,
  type SupportedElementorFreeTarget,
} from "./catalog";

export {
  ConversionReportSchema,
  ConversionResultSchema,
  buildConversionReport,
  buildConversionResult,
  canonicalizeConversionReport,
  decisionsCoveringIrTree,
  deriveOutcome,
  normalizeReasonCode,
  reasonCodeForCustomFailure,
  type ConversionReport,
  type ConversionResult,
  type ReportDiagnostic,
  type ReportNodeEntry,
} from "./report";

export { convert, type ConvertOptions } from "./convert";
export {
  convertSource,
  ConvertSourceOptionsSchema,
  type ConvertSourceOptions,
} from "./convert-source";

export {
  convertSectionInput,
  resolveSectionInput,
  normalizeVirtualFiles,
  normalizeVirtualPath,
  resolveEntryPath,
  resolveImportGraph,
  resolveModulePath,
  resolveExistingVirtualModule,
  matchPathAlias,
  normalizeAliasMappedPath,
  resolveAliasToVirtualModule,
  toConvertSourceOptions,
  SECTION_INPUT_LIMITS,
  SectionInputError,
  type VirtualFiles,
  type ResolvedSection,
  type ResolveSectionInputOptions,
  type ResolveSectionResult,
  type ConvertSectionInputOptions,
  type SectionDiagnostic,
  type DependencyGraph,
  type PathAliases,
} from "./section-input";

/** Phase 13a–13e: project VFS + structure + per-route convert + dependency registry. */
export {
  extractProjectZip,
  normalizeZipEntryPath,
  PROJECT_LIMITS,
  resolveProjectLimits,
  PROJECT_IGNORE_SEGMENT_NAMES,
  matchIgnoredPath,
  classifyProjectFileBytes,
  detectSingleRootPrefix,
  createProjectVirtualFSFromTextFiles,
  ProjectZipError,
  detectFramework,
  analyzeProjectStructure,
  discoverProjectRoutes,
  discoverNextAppRoutes,
  discoverNextPagesRoutes,
  discoverSpaRoutes,
  resolveSpaEntry,
  convertProject,
  convertProjectAsync,
  buildConversionUnit,
  convertRouteUnit,
  collectRouteScopedCss,
  stripCssImportQuery,
  listRootCssSourceModules,
  PROJECT_ROUTE_GRAPH_LIMITS,
  ELEMENTOR_FREE_PAGE_TEMPLATES,
  applyDocumentPageLayout,
  documentHasFullBleedLandingEvidence,
  isAllowedElementorFreePageTemplate,
  isFullBleedLandingContainer,
  resolveProjectPageTemplate,
  DEPENDENCY_REGISTRY,
  lookupDependencyRegistry,
  packageNameFromSpecifier,
  listRegisteredPackages,
  discoverExternalImports,
  analyzeRouteDependencies,
  applyDependencyAnalysisToUnit,
  dependencyForcesRoutePartial,
  getAdapter,
  classifyProjectPathAdmission,
  discoverRouteAssets,
  IMAGE_ASSET_EXTENSIONS,
  isImageAssetPath,
  resolveAssetSpecifierToPath,
  lookupAssetInVfs,
  runProjectMediaPipeline,
  rewriteConversionUnitMediaUrls,
  createWordPressMediaClient,
  readWordPressMediaConfigFromEnv,
  WP_MEDIA_ENV,
  MEDIA_OPTIMIZE_ENV,
  MEDIA_OPTIMIZE_LIMITS,
  optimizeAsset,
  isMediaOptimizeEnabledFromEnv,
  resetSharpCacheForTests,
  type ProjectLimits,
  type ProjectLimitsInput,
  type ProjectPathAdmissionKind,
  type ProjectVirtualFS,
  type ProjectVfsFile,
  type ProjectTextFile,
  type ProjectBinaryFile,
  type ProjectIgnoredEntry,
  type ProjectDiagnostic,
  type ProjectVirtualFsStats,
  type ExtractProjectZipOptions,
  type ExtractProjectZipResult,
  type ProjectManifest,
  type ProjectRoute,
  type ProjectFrameworkKind,
  type ProjectStructureAnalysis,
  type DiscoverRoutesResult,
  type ConversionUnit,
  type RouteConversionResult,
  type ProjectConversionResult,
  type ConvertProjectOptions,
  type DocumentPageLayoutMode,
  type ElementorFreePageTemplate,
  type DependencyCategory,
  type DependencyCapabilityStatus,
  type DependencyCapability,
  type RouteDependencyAnalysis,
  type ProjectAsset,
  type ProjectAssetReference,
  type RouteAssetDiscoveryResult,
  type ProjectMediaClient,
  type ProjectMediaUploadRequest,
  type ProjectMediaUploadResult,
  type ProjectMediaOptimizationMeta,
  type ProjectMediaSummary,
  type ProjectMediaPipelineOptions,
  type MediaOptimizationStatus,
  type AssetOptimizationResult,
} from "./project";

export {
  parseReactSource,
  analyzeReactAst,
  analyzeReactSource,
  ReactParseError,
  ParseReactSourceOptionsSchema,
  AnalyzeReactOptionsSchema,
  type ParseReactSourceOptions,
  type AnalyzeReactOptions,
  type ParsedReactSource,
  type AnalyzeReactResult,
  type ReactSourceLanguage,
} from "./parse";

export {
  resolveStyles,
  ResolveStylesOptionsSchema,
  STYLE_MERGE_PRECEDENCE,
  resolveTailwindClasses,
  resolveTailwindUtility,
  parseCssSources,
  resolveInlineStyleRaw,
  mergeIrStyles,
  extractThemeTokens,
  resolveThemeColorToken,
  canonicalizeCssColor,
  oklchToCssColor,
  type ResolveStylesOptions,
  type ResolveStylesResult,
  type ThemeTokens,
} from "./styles";

export {
  convertToNativeElementor,
  convertToElementor,
  convertIrNodeWithFallback,
  convertCustomFallback,
  serializeIrNodeHtml,
  serializeScopedCss,
  escapeHtmlAttr,
  escapeHtmlText,
  findUnsafeCustomPatterns,
  elementorIdFromIrId,
  NativeStrategySchema,
  mapIrStyleToSettings,
  cascadeMobileFirstToElementorTiers,
  toBoxShadow,
  toSlider,
  toGridColumns,
  isButtonLikeLink,
  type ConvertToNativeOptions,
  type ConvertToElementorOptions,
  type NativeStrategy,
  type NativeNodeDecision,
  type NativeConversionResult,
  type ElementorDocument,
  type ElementorElement,
  type ElementorSettings,
} from "./rules";

export {
  validateElementorDocument,
  canonicalizeElementorJson,
  flattenDecisions,
  toElementorElement,
  type EmitValidationResult,
  type ElementorElementDraft,
} from "./emit";

export {
  REQUIRED_ELEMENTOR_FREE_VERSION,
  resolveElementorFree424SourceRoot,
  readElementorVersion,
  probeRuntimeEnvironment,
  buildElementorSourceInventory,
  extractGetName,
  extractAddControlIds,
  MVP_WIDGETS,
  validateStaticElementorCompatibility,
  scanProContamination,
  getRuntimeImportStatus,
  type ElementorSourceInventory,
  type StaticCompatResult,
  type StaticCompatViolation,
  type RuntimeImportStatus,
  type RuntimeEnvironmentStatus,
} from "./compat";

export {
  probePhase11Runtime,
  runSetup,
  writeReport,
  readRuntimeEnv,
  generateDocumentFromFixture,
  importDocumentJson,
  collectWidgets,
  flattenWidgetTypes,
  collectResponsiveKeys,
  findFirstWidget,
  EXPECTED_NATIVE_TYPES,
  emptyBlockedReport,
  wpCli,
  createHarnessWordPressMediaClient,
  readHarnessWordPressMediaConfig,
  harnessWordPressMediaPath,
  type RuntimeValidationReport,
  type FixtureRuntimeResult,
  type RuntimeStatus,
  type VisualStatus,
} from "./runtime";
